"""add_user_role

Revision ID: 96349b02d204
Revises: 2075d2953034
Create Date: 2026-06-20 13:02:07.360060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96349b02d204'
down_revision: Union[str, Sequence[str], None] = '2075d2953034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'sla_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'on_time'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'sla_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'on_time'::character varying"))
    # ### end Alembic commands ###
